win-build:
	rm -f /mnt/c/Users/tinky/Desktop/holbify.exe
	x86_64-w64-mingw32-g++ -g -Wall -o holbify.exe main.cpp functions_init.cpp functions_events.cpp functions_tools.cpp -I/mnt/c/msys64/mingw64/include/glib-2.0 -I/mnt/c/msys64/mingw64/include -I/mnt/c/msys64/mingw64/include/glibmm-2.4 -I/mnt/c/msys64/mingw64/lib/glibmm-2.4/include -L/usr/x86_64-w64-mingw32/lib -lgstreamer-1.0 -lgstreamermm-1.0 -lgsttag-1.0 -lgtkmm-3.0 -lglibmm-2.4
